#公共/开发配置
spring:
  datasource:
    url: jdbc:mysql://120.24.161.55:3306/mycat2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: krMw6ZdyB(2l
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.gj1913894.web.starter: debug
feign:
  client:
    scan:
      pkg: com.gj1913894.web.starter.service.third
server:
  port: 8000