#公共/开发配置
server:
  port: 8000

debug: true
logging:
  level:
    com.gj1913894.web.starter: debug
    org.mariadb.jdbc: debug

spring:
  datasource:
    url: jdbc:mariadb://120.24.161.55:3306/mycat2
    username: root
    password: krMw6ZdyB(2l
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        enablePacketDebug: true
        useServerPrepStmts: true
        cachePrepStmts: true

feign:
  client:
    scan:
      pkg: com.gj1913894.web.starter.service.http


#mybatis.type-aliases-package=tk.mybatis.springboot.model
#mybatis.mapper-locations=classpath:mapper/*.xml