#公共/开发配置
server:
  port: 8000

debug: true
logging:
  level:
    com.gj1913894.web.starter: debug
    org.mariadb.jdbc: debug
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: trace

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mycat2
    username: root
    password: krMw6ZdyB(2l
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        enablePacketDebug: true
        useServerPrepStmts: true
        cachePrepStmts: true

feign:
  client:
    scan:
      pkg: com.gj1913894.web.starter.service.http

#mybatis & mapper
mybatis:
  mapper-locations: classpath:/com/gj1913894/web/starter/mapper/*Mapper.xml
  type-aliases-package: com.gj1913894.web.starter.entity

mapper:
#  mappers: com.gj1913894.web.starter.mapper
  not-empty: false
  identity: MYSQL
  use-java-type: true
  style: normal